### ISSUE TITLE
Minor: Adding westend to Metamask

### ISSUE THREAD

**Issue by kianenigma** [paritytech/contract-issues#10]
I have both Talisman and Metamask. Clicking the button to add a network will first pop up talisman. Only after a refresh, I can add Metamask. 

I can imagine that Talisman is a fully ETH compatible wallet, so they can be used inter-change-ably. 

Not sure if possible, but perhaps we can change the behavior of that wallet to only wake up Metamask. 

Only Polkadot native people will have Talisman. Won't likely be an issue for a former ETH solidity dev trying this.

**Comment by block-scouthelp** [comment]
@kianenigma It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://dapps-exploreonsite.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by pgherveou** [comment]
We changed the button here
https://contracts.polkadot.io/connect-to-asset-hub
to use a wallet sdk, that should prompt you first which wallet you want to use.

Does that fix your issue?
