### ISSUE TITLE
Logs emitted by Solidity don't show up in REMIX

### ISSUE THREAD

**Issue by athei** [paritytech/contract-issues#4]
I modified the example `1_Storage.sol` to emit a simple log:
```Solidity

event LogMessage(string message);

function store_value(uint256 num) public {
    emit LogMessage("called store_value");
    number = num;
}
```

When I run submit the `store_value` as transaction from REMIX the log doesn't show up:
<img width="724" alt="Screenshot 2024-11-07 at 01 33 17" src="https://github.com/user-attachments/assets/13579119-db83-41bc-a393-cda0a5a99111">

I verified that the event was actually emitted by looking up [the extrinsic](https://assethub-westend.subscan.io/tx/0x7f2ee51c4cba12f2ef1f6eee775241bbe6e91b5feaf2edebaf51df811824c961) in SubScan:
<img width="1221" alt="Screenshot 2024-11-07 at 01 34 47" src="https://github.com/user-attachments/assets/d6780281-4b4a-4c7f-9809-84d8667b0d59">

I also dry-ran it and made sure that the event is there:
<img width="1554" alt="Screenshot 2024-11-07 at 01 36 46" src="https://github.com/user-attachments/assets/bfb2b01e-8e8e-44ca-94ee-1e07f30abf62">

I didn't debug whether the RPC proxy doesn't return the log or whether REMIX is the cuprit.

**Comment by pgherveou** [comment]
fixed by https://github.com/paritytech/polkadot-sdk/pull/6393 [commit](https://github.com/paritytech/polkadot-sdk/pull/6393/commits/4608073a52ed998b62af87fc74c5e0046c1dcf63)
