### ISSUE TITLE
Transition to `REMIXD` confusing

### ISSUE THREAD

**Issue by Jan-Jan** [paritytech/contract-issues#7]
On https://contracts.polkadot.io/deploy-your-first-contract/ when transitioning to "Connect to Your Local Filesystem" all previously compiled contracts are lost. And in the subsequent section "Generate and Deploy DApp UI with Quick DApp Plugin" there is then no smart contract to connect to.

* Potential solution, would be to include in the instructions how to populate the local filesystem first. Can we have a git repo they can clone?
* Open question: Would it be simpler in the docs to the compile and deploy from local filesystem instead?
* Bonus: Explain how previously deployed contracts could be restored.

**Comment by smiasojed** [comment]
"Open question: Would it be simpler in the docs to the compile and deploy from local filesystem instead?"
I think that most people will not install REMIXD and will just use REMIX without access to the local FS.
I think that we should remove REMIXD section from tutorial.
@Jan-Jan WDYT?

**Comment by Jan-Jan** [comment]
In the short term (i.e. min requirements for Westend public launch): 

1. Agreed,  it is better to remove REMIXD than to use the documentation as is. 
3. We should still update the doc to tell/show people to save contract address after deploying. (Telling them it is difficult to find it again otherwise.)

Thereafter, we can (as you suggested):

4. Add a section showing users how to download the zip file, and use REMIXD (I prefer this over the repo idea I had).
5. And show them how to access the contracts they previously deployed.
